#Information injected by terraform
projectValues:
  stage: "SET_BY_TERRAFORM"
  traefikElbId: "SET_BY_TERRAFORM"
  adminDomain: "SET_BY_TERRAFORM"
  storageClassKmsKeyId: "SET_BY_TERRAFORM"

global:
  helm:
    #From which Helm repo the charts should be pulled
    repoURL: https://charts.iits.tech/
    # Default Helm Parameters which are injected into every chart
    parameters:
      ingressRoute.adminDomain: "{{.Values.projectValues.adminDomain}}"

charts:
  argocd-config:
    namespace: argocd
    targetRevision: 0.4.1
    parameters:
      ingressRoute.certificate.enabled: "true"
      ingressRoute.entryPointName: "websecure"

  otc-storage-classes:
    namespace: storage-classes
    targetRevision: 1.0.0
    parameters:
      "kmsId": "{{.Values.projectValues.storageClassKmsKeyId}}"

  traefik:
    namespace: routing
    targetRevision: 10.22.0-internal-svc
    # Overrides default Helm Parameters
    parameters:
      "traefik.deployment.replicas": "1"
      "traefik.service.annotations.kubernetes\\.io\\/elb\\.id": "{{.Values.projectValues.traefikElbId}}"

  cert-manager:
    namespace: cert-manager
    targetRevision: 0.2.3
    parameters:
      "clusterIssuer.http.email": "my-mail@mail.com"

  basic-auth-gateway:
    namespace: routing
    targetRevision: 0.5.1
    parameters:
      "ingressRoute.domain": "{{.Values.projectValues.adminDomain}}"

  kafka:
    namespace: kafka
    targetRevision: 22.1.5
    parameters:
      "kafka.replicaCount": "1"

  # Remote chart from public helm repo
  bitnami-kafka:
    namespace: bitnami-kafka # Which namespace should the service be deployed
    repoURL: "https://charts.bitnami.com/bitnami" # Helm repo URL by default it takes the helm repo URL from line 11
    targetRevision: 22.1.5 # Helm Chart Repo URL
    overrideChartName: kafka # You can override the chart name
    disableAutoSync: false # If set to true the sync will not happen automatically, you need to do it manually over the UI
    parameters:
      "kafka.replicaCount": "1"

  # Local chart for development purposes
  akhq:
    namespace: kafka
    repoURL: "https://github.com/iits-consulting/otc-infrastructure-charts-template.git"
    targetRevision: "main"
    path: "local-charts/akhq"

  # Override values with local values file
  iits-admin-dashboard:
    namespace: admin
    targetRevision: "1.2.0"
    # values files needs to be inside this chart
    valueFile: "value-files/admin-dashboard/values.yaml"